name: YmgGacha
version: 1.0.0
main: ymggacha\src\yomogi_server\ymggacha\YmgGachaPlugin
api: 4.0.0
author: RarkHopper
depend:
  - WorldInv
virions:
  - Gacha
  - Commando
  - FireworkParticle
  - Modals
permissions:
  ymggacha.command.op:
    description: "Allows the user to run the op command"
    default: op # can also be false, or op
  ymggacha.command.public:
    description: "Allows the user to run the public command"
    default: true # can also be false, or op
