<?php

namespace lazyperson0710\ticket;

use pocketmine\player\Player;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase {

    //    private static TicketAPI $instance;
    //    private \SQLiteDatabase $db;//sqlわからん
    public function onEnable(): void {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    /*public static function getInstance(): TicketAPI {//API部分は別にしないといけないので後程修正
        if (!isset(self::$instance)) {
            self::$instance = new TicketAPI();
        }
        return self::$instance;
    }*/
    public function createData(Player $player) {
        //自身のデータを作成するだけjoinとかでつかいたい
    }

    public function checkData(Player $player): int {
        //データをチェックするだけintで数量だけ返す
    }

    public function addTicket(Player $player, int $increase) {
        //増加分だけ自身のticketを増やす
    }

    public function reduceTicket(Player $player, int $reduce) {
        //増加分だけ自身のticketを増やす
    }

}