<?php

namespace lazyperson0710\ticket;

use pocketmine\player\Player;
use pocketmine\plugin\PluginBase;

class TicketAPI extends PluginBase {

    private static TicketAPI $instance;

    public static function getInstance(): TicketAPI {
        if (!isset(self::$instance)) {
            self::$instance = new TicketAPI();
        }
        return self::$instance;
    }

    public function onEnable(): void {
        parent::onEnable(); // TODO: Change the autogenerated stub
    }

    public function createData(Player $player) {
        //自身のデータを作成するだけjoinとかでつかいたい
    }

    public function checkData(Player $player): int {
        //データをチェックするだけintで数量だけ返す
    }

    public function addTicket(Player $player, int $increase) {
        //増加分だけ自身のticketを増やす
    }

    public function reduceTicket(Player $player, int $reduce) {
        //増加分だけ自身のticketを増やす
    }

}