name: book
main: book\main
api: 4.0.0
version: 1.2.0
commands:
  book:
    usage: /book
    description: 50円で署名済みの本を一冊複製する
    permission: book.command.book
    author: Re
permissions:
  book.command.book:
    default: true