name: LoginBonusItem
main: deceitya\lbi\Main
version: 1.0.0
api:
  - 4.0.0
load: POSTWORLD
author: deceitya
description: ログインボーナスアイテム
commands:
  bonuscollect:
    usage: "/bonuscollect"
    description: "保留しているログインボーナスを受け取ります(通常ログインボーナスの受け取りを行う事はできません)"
    permission: LoginBonusItem.command
  forcebonuscollect:
    usage: "/forcebonuscollect 回数 ユーザー名"
    description: "ログインボーナスを錬成します。/forcebonuscollect <回数> <ユーザー名>(10回以上指定しました場合、サーバーフリーズします)"
    permission: LoginBonusItem.op
permissions:
  LoginBonusItem.op:
    default: op
  LoginBonusItem.command:
    default: true