# "id:meta:個数:名前:説明:エンチャID:エンチャレベル"
1:
  - "16:0:8:樫の原木:ログインボーナスで交換したアイテムです::"
  - "16:1:8:トウヒの原木:ログインボーナスで交換したアイテムです::"
  - "16:2:8:白樺の原木:ログインボーナスで交換したアイテムです::"
  - "16:3:8:ジャングルの原木:ログインボーナスで交換したアイテムです::"
  - "162:0:8:アカシアの原木:ログインボーナスで交換したアイテムです::"
  - "162:1:8:黒樫の原木:ログインボーナスで交換したアイテムです::"
3:
  - "1:0:16:石:ログインボーナスで交換したアイテムです::"
  - "1:1:16:花崗岩:ログインボーナスで交換したアイテムです::"
  - "1:3:16:閃緑岩:ログインボーナスで交換したアイテムです::"
  - "1:5:16:安山岩:ログインボーナスで交換したアイテムです::"
  - "1:2:16:磨かれた花崗岩:ログインボーナスで交換したアイテムです::"
  - "1:4:16:磨かれた閃緑岩:ログインボーナスで交換したアイテムです::"
  - "1:6:16:磨かれた安山岩:ログインボーナスで交換したアイテムです::"
  - "98:0:8:石レンガ:ログインボーナスで交換したアイテムです::"
5:
  - "267:0:1:鉄の剣:ログインボーナスで交換したアイテムです::"
  - "257:0:1:鉄のツルハシ:ログインボーナスで交換したアイテムです::"
  - "258:0:1:鉄のオノ:ログインボーナスで交換したアイテムです::"
  - "256:0:1:鉄のシャベル:ログインボーナスで交換したアイテムです::"
  - "292:0:1:鉄のクワ:ログインボーナスで交換したアイテムです::"
  - "261:0:1:弓:ログインボーナスで交換したアイテムです::"
  - "262:0:16:矢:ログインボーナスで交換したアイテムです::"
  - "364:0:8:スライムゼリー:ログインボーナスで交換したアイテムです::"
  - "354:0:3:ケーキ:ログインボーナスで交換したアイテムです::"
  - "464:0:16:乾燥昆布:ログインボーナスで交換したアイテムです::"
10:
  - "276:0:1:鋭いダイヤの剣:これは、、、鋭い！！！:9:3"
  - "278:0:1:頑丈なダイヤのツルハシ:なんでダイヤなのにこいつだけめっちゃ硬いねん！？:17:5"
15:
  - "278:0:1:なぜか早く掘れるダイヤのツルハシ[lv8]:早く掘れる！でもなんで？？？:15:8"
  - "384:0:128:エンチャントビン[2st]:さあレベルを使って修繕しよう！！::"
  - "130:0:1:エンダーチェスト:置くとこのメッセージは消えてしまう、、、くそっ::"
20:
  - "52:0:1:レベルブロック[1個]:れべべべるうううううう::"
  - "218:0:1:シェルカーボックス:持ち運びが楽になる！！え？倉庫があるから必要ないって？F**k!!!::"
