---
name: ItemEditor
main: aieuo\itemEditor\Main
version: 1.0.1
api: 4.0.0
author: aieuo
commands:
  edit:
    description: アイテム情報の変更
    usage: /edit
    permission: itemedit.command.edit
permissions:
  itemedit.command.edit:
    default: op
...
