  --
  items:

    #アイテーーーーーーーーーーーーーーーーーーーーーーム

    twitter: ##ついったーちゃん
      name: ついったーちゃん
      namespace: "custom:ついったーちゃん"
      id: 1000
      meta: 0
      max_stack_size: 1
      texture: twitter
      allow_off_hand: true
      add_creative_inventory: true

    storage: ##ストレージボックス
      name: ストレージボックス
      namespace: "custom:ストレージボックス"
      id: 1101
      meta: 0
      max_stack_size: 1
      texture: storage
      allow_off_hand: true
      add_creative_inventory: true

    5000en: ##5000円
      name: 5000円
      namespace: "custom:5000円"
      id: 1102
      meta: 0
      max_stack_size: 64
      texture: 5000en
      allow_off_hand: true
      add_creative_inventory: true

    10000en: ##10000円
      name: 10000円
      namespace: "custom:10000円"
      id: 1103
      meta: 0
      max_stack_size: 64
      texture: 10000en
      allow_off_hand: true
      add_creative_inventory: true

    #ピッケル

    pickaxe_1: ##疾風のつるはし
      name: 疾風のつるはし
      namespace: "custom:疾風のつるはし"
      tool: true
      id: 1501
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5 # pickaxe | shovel | sword | axe | hoe
      texture: blaze_rod # required for sword
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_2: ##窓一郎の炯眼
      name: 窓一郎の炯眼
      namespace: "custom:窓一郎の炯眼"
      tool: true
      id: 1502
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_3: ##おもちゃのつるはし
      name: おもちゃのつるはし
      namespace: "custom:おもちゃのつるはし"
      tool: true
      id: 1503
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_4: ##重いつるはし
      name: 重いつるはし
      namespace: "custom:重いつるはし"
      tool: true
      id: 1504
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_5: ##満福つるはし
      name: 満福つるはし
      namespace: "custom:満福つるはし"
      tool: true
      id: 1505
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_6: ##暗夜行山
      name: 暗夜行山
      namespace: "custom暗夜行山:"
      tool: true
      id: 1506
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_7: ##溶岩泳者の友
      name: 溶岩泳者の友
      namespace: "custom:溶岩泳者の友"
      tool: true
      id: 1507
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_8: ##古びたつるはし
      name: 古びたつるはし
      namespace: "custom:古びたつるはし"
      tool: true
      id: 1508
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_9: ##呪いのつるはし
      name: 呪いのつるはし
      namespace: "custom:呪いのつるはし"
      tool: true
      id: 1509
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_10: ##溶鉱炉
      name: 溶鉱炉
      namespace: "custom:溶鉱炉"
      tool: true
      id: 1510
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_11: ##アルケミピッケル
      name: アルケミピッケル
      namespace: "custom:アルケミピッケル"
      tool: true
      id: 1511
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_12: ##鉱石より愛を込めて
      name: 鉱石より愛を込めて
      namespace: "custom:鉱石より愛を込めて"
      tool: true
      id: 1512
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    pickaxe_13: ##ハイドロゲル
      name: ハイドロゲル
      namespace: "custom:ハイドロゲル"
      tool: true
      id: 1513
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: blaze_rod
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    #そのた！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

    obsidian_breaker: ##Obsidian Breaker
      name: Obsidian Breaker
      namespace: "custom:obsidian_breaker"
      tool: true
      id: 1601
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: obsidian_breaker
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    glowstone_breaker: ##Glowstone Breaker
      name: Glowstone Breaker
      namespace: "custom:glowstone_breaker"
      tool: true
      id: 1602
      meta: 0
      mining_speed: 2
      tool_type: 4
      tool_tier: 5
      texture: glowstone_breaker
      allow_off_hand: true
      add_creative_inventory: true
      durable: true
      max_durability: 150

    #フーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーード

    apple_candy: ##いちご飴
      name: いちご飴
      namespace: "custom:いちご飴"
      food: true
      id: 1800
      meta: 0
      max_stack_size: 16
      texture: apple_candy
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    american_hotdog: ##アメリカンドッグ
      name: アメリカンドッグ
      namespace: "custom:アメリカンドッグ"
      food: true
      id: 1801
      meta: 0
      max_stack_size: 16
      texture: american_hotdog
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    churu_cat: ##ちゅーる
      name: ちゅーる
      namespace: "customちゅーる:"
      food: true
      id: 1802
      meta: 0
      max_stack_size: 16
      texture: churu_cat
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    churu_dog: ##ちゅーる2
      name: ちゅーる2
      namespace: "custom:ちゅーる2"
      food: true
      id: 1803
      meta: 0
      max_stack_size: 16
      texture: churu_dog
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    shaved_ice: ##かきごおり
      name: かきごおり
      namespace: "custom:かきごおり"
      food: true
      id: 1804
      meta: 0
      max_stack_size: 16
      texture: shaved_ice
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    takoyaki: ##たこ焼き
      name: たこ焼き
      namespace: "custom:たこ焼き"
      food: true
      id: 1805
      meta: 0
      max_stack_size: 16
      texture: takoyaki
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    monster_big: ##もんすたー
      name: もんすたー
      namespace: "custom:もんすたー"
      food: true
      id: 1806
      meta: 0
      max_stack_size: 16
      texture: monster_big
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    monster_pipeline_punch: ##もんすたー2
      name: もんすたー2
      namespace: "custom:もんすたー2"
      food: true
      id: 1807
      meta: 0
      max_stack_size: 16
      texture: monster_pipeline_punch
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    honey: ##はちみつ
      name: はちみつ
      namespace: "custom:はちみつ"
      food: true
      id: 1808
      meta: 0
      max_stack_size: 16
      texture: honey
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    christmas_candy: ##キャンディケイン
      name: キャンディケイン
      namespace: "custom:キャンディケイン"
      food: true
      id: 1809
      meta: 0
      max_stack_size: 16
      texture: christmas_candy
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2

    christmas_cookie: ##ジンジャーマンクッキー
      name: ジンジャーマンクッキー
      namespace: "custom:ジンジャーマンクッキー"
      food: true
      id: 1810
      meta: 0
      max_stack_size: 16
      texture: christmas_cookie
      allow_off_hand: true
      add_creative_inventory: true
      can_always_eat: true
      nutrition: 1
      saturation: 2
    ...
