name: MiningTools4
main: deceitya\miningtools4\Main
version: 1.1.0
api: 4.0.0

commands:
  mt4:
    usage: "/mt4"
    description: "MiningToolsを購入"
    permission: miningtools.command.mt4
permissions:
  miningtools.command.mt4:
    description: "allow user using mt4 command"
    default: op
