name: OrgInventory
main: hototya\inventory\OrgInventory
version: 1.0.1
api:
  - 4.0.0
load: POSTWORLD
website: https://github.com/hototya/OrgInventory
author: hototya
commands:
  inv:
    description: プレイヤーインベントリをID順に整理します
    usage: /inv
    permission: inventory.command.inv

permissions:
  inventory.command.inv:
    default: true
    description: permission that allows player to use /org