name: BonusConvert
main: Deceitya\BonusConvert\BonusConvertPlugin
version: 1.0.0
api: 4.0.0
load: POSTWORLD
author: deceitya
description: ログボ変換
commands:
  bonusconvert:
    usage: "/bonusconvert"
    description: ログインボーナス交換フォームを開きます
    permission: bonuscon.command.bonusconvert
permissions:
  bonuscon.command.bonusconvert:
    description: Allows the user to run the bonus command
    default: true