---
name: ReportSystem
main: nuthmc\report\Loader
api:
  - 4.0.0
version: 2.1.0
author: NuthMC
commands:
  report:
    description: "レポートをdiscordに送信します"
    permission: use.r
permissions:
  use.r:
    default: true
...
