---
blocks:
  # mechanism
  command_block: false
  dispenser: false
  door: true
  dropper: false
  fence_gate: true
  hopper: true
  note_block: false
  rail: false
  redstone_lamp: true
  skull: false
  tnt: false
  trapdoor: true

  # power
  button: true
  daylight_sensor: true
  jukebox: false
  lever: true
  observer: false
  redstone_block: true
  redstone_torch: true
  pressure_plate: true
  trapped_chest: true
  tripwire: false
  weighted_pressure_plate: true

  # transmission
  comparator: true
  redstone_wire: true
  repeater: true
...
